packages:
  - "apps/*"
  - "packages/*"
overrides:
  glob: "^13.0.6"
  lodash: "^4.18.1"
  multer: "^2.1.1"
  picomatch: "^4.0.4"
  tmp: ">=0.2.6"
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: true
