FROM node:22-bookworm-slim AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
WORKDIR /app

RUN corepack enable

ARG NEXT_PUBLIC_API_BASE_URL=http://localhost:3100/api/v1
ARG NEXT_PUBLIC_PUBLIC_API_BASE_URL=http://localhost:3100/api/v1
ARG NEXT_PUBLIC_CITIZEN_WEB_BASE_URL=http://localhost:3102
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_CITIZEN_WEB_BASE_URL=$NEXT_PUBLIC_CITIZEN_WEB_BASE_URL

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.base.json ./
COPY apps ./apps
COPY packages ./packages

RUN pnpm install --frozen-lockfile
RUN PRISMA_GENERATE_NO_ENGINE=true pnpm db:generate
RUN pnpm build

FROM node:22-bookworm-slim AS runtime

ENV NODE_ENV=production
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
WORKDIR /app

RUN corepack enable

COPY --from=base /app /app

CMD ["node", "-e", "console.error('Set a service command in docker-compose.prod.yml'); process.exit(1)"]
